
message("_desktop_ambient_5.cmake begin ------------")

if(${DESKTOP_AMBIENT})
    # DESKTOP_AMBIENT are dependant just on linux kernel version and glib version?

    message(STATUS "_desktop_ambient_5.cmake DESKTOP_AMBIENT is set")

add_subdirectory(operating_system-posix/aura_posix)
add_subdirectory(operating_system-${PLATFORM_NAME}/aura_${PLATFORM_NAME})
add_subdirectory(operating_system-posix/windowing_posix)
add_subdirectory(operating_system-${PLATFORM_NAME}/node_${PLATFORM_NAME})
# if(${LXDE_DESKTOP})
#     message(STATUS "operating_system/CMakeLists.txt LXDE_DESKTOP")
#     add_subdirectory(operating_system-posix/windowing_x11)
#     add_subdirectory(operating_system-posix/node_gdk)
#     add_subdirectory(operating_system-posix/node_gtk3)
#     add_subdirectory(operating_system-posix/node_gnome)
#     add_subdirectory(operating_system-${PLATFORM_NAME}/desktop_environment_gnome)
# endif()
#if(XFCE_DESKTOP)
#    add_subdirectory(operating_system-posix/windowing_x11)
#    add_subdirectory(operating_system-posix/node_gdk)
#    add_subdirectory(operating_system-posix/node_gtk3)
#    add_subdirectory(operating_system-posix/node_xfce)
#    add_subdirectory(operating_system-${PLATFORM_NAME}/desktop_environment_xfce)
#endif()
if(${GTK_BASED_DESKTOP})
    #add_subdirectory(operating_system-posix/windowing_x11)
    #add_subdirectory(operating_system-posix/node_gdk)
    add_subdirectory(operating_system-posix/gnome_library)
    add_subdirectory(operating_system-posix/acme_windowing_g)
    if(${HAS_WAYLAND})
        add_subdirectory(operating_system-posix/windowing_wayland)
    endif()
    if(${HAS_GTK4})
        #add_subdirectory(operating_system-posix/windowing_system_gtk4)
        add_subdirectory(operating_system-posix/accessibility_gtk4)
        add_subdirectory(operating_system-posix/acme_windowing_gtk4)
        add_subdirectory(operating_system-posix/innate_ui_gtk4)
        add_subdirectory(operating_system-posix/windowing_gtk4)
        add_subdirectory(operating_system-posix/node_gtk4)
        add_subdirectory(operating_system-${PLATFORM_NAME}/operating_ambient_gtk4)
    elseif(${HAS_GTK3})
        #add_subdirectory(operating_system-posix/windowing_system_gtk3)
        add_subdirectory(operating_system-posix/acme_windowing_gtk3)
        add_subdirectory(operating_system-posix/innate_ui_gtk3)
        add_subdirectory(operating_system-posix/windowing_gtk3)
        add_subdirectory(operating_system-posix/node_gtk3)
        add_subdirectory(operating_system-${PLATFORM_NAME}/operating_ambient_gtk3)
    endif()
    add_subdirectory(operating_system-posix/node_gtk_based)
elseif(${KDE_DESKTOP})
    add_subdirectory(operating_system-posix/acme_windowing_q)
    add_subdirectory(operating_system-posix/innate_ui_q)
    add_subdirectory(operating_system-posix/windowing_q)
    add_subdirectory(operating_system-posix/node_q)
    if(${HAS_KDE6})
        #3add_subdirectory(operating_system-posix/windowing_system_gtk4)
        add_subdirectory(operating_system-posix/acme_windowing_q6)
        add_subdirectory(operating_system-posix/innate_ui_q6)
        add_subdirectory(operating_system-posix/windowing_q6)
        add_subdirectory(operating_system-posix/acme_windowing_kde6)
        add_subdirectory(operating_system-posix/innate_ui_kde6)
        add_subdirectory(operating_system-posix/windowing_kde6)
        add_subdirectory(operating_system-posix/node_kde6)
        add_subdirectory(operating_system-${PLATFORM_NAME}/operating_ambient_kde6)

    elseif(${HAS_KDE5})
        #3add_subdirectory(operating_system-posix/windowing_system_gtk4)
        add_subdirectory(operating_system-posix/acme_windowing_q5)
        add_subdirectory(operating_system-posix/innate_ui_q5)
        add_subdirectory(operating_system-posix/windowing_q5)
        add_subdirectory(operating_system-posix/acme_windowing_kde5)
        add_subdirectory(operating_system-posix/innate_ui_kde5)
        add_subdirectory(operating_system-posix/windowing_kde5)
        add_subdirectory(operating_system-posix/node_kde5)
        add_subdirectory(operating_system-${PLATFORM_NAME}/operating_ambient_kde5)

    endif()
elseif(${LXQT_DESKTOP})
    add_subdirectory(operating_system-posix/acme_windowing_q)
    add_subdirectory(operating_system-posix/innate_ui_q)
    add_subdirectory(operating_system-posix/windowing_q)
    add_subdirectory(operating_system-posix/node_q)
    #add_subdirectory(operating_system-posix/common_kde)
    if(${HAS_LXQ2})
        #3add_subdirectory(operating_system-posix/windowing_system_gtk4)
        add_subdirectory(operating_system-posix/acme_windowing_q6)
        add_subdirectory(operating_system-posix/innate_ui_q6)
        add_subdirectory(operating_system-posix/windowing_q6)
        add_subdirectory(operating_system-posix/acme_windowing_lxq2)
        add_subdirectory(operating_system-posix/innate_ui_lxq2)
        add_subdirectory(operating_system-posix/windowing_lxq2)
        add_subdirectory(operating_system-posix/node_lxq2)
        add_subdirectory(operating_system-${PLATFORM_NAME}/operating_ambient_lxq2)

   elseif(${HAS_LXQ1})
        add_subdirectory(operating_system-posix/acme_windowing_q5)
        add_subdirectory(operating_system-posix/innate_ui_q5)
        add_subdirectory(operating_system-posix/windowing_q5)
        add_subdirectory(operating_system-posix/acme_windowing_lxq1)
        add_subdirectory(operating_system-posix/innate_ui_lxq1)
        add_subdirectory(operating_system-posix/windowing_lxq1)
        add_subdirectory(operating_system-posix/node_lxq1)
        add_subdirectory(operating_system-${PLATFORM_NAME}/operating_ambient_lxq1)

    endif()
endif()
endif()

message("_desktop_ambient_5.cmake end ------------")
