cmake_minimum_required(VERSION 3.17)
project(input_xinput CXX)
find_package(PkgConfig REQUIRED)
pkg_check_modules(INPUT_XINPUT REQUIRED IMPORTED_TARGET x11 xi)
set(input_xinput_sources _.cpp _.h _factory.cpp input.cpp input.h)
add_library(input_xinput SHARED ${input_xinput_sources})
add_library(static_input_xinput STATIC ${input_xinput_sources})
foreach(input_target IN ITEMS input_xinput static_input_xinput)
   target_compile_features(${input_target} PRIVATE cxx_std_20)
   target_compile_definitions(${input_target} PRIVATE _input_xinput_project)
   target_include_directories(${input_target} PRIVATE
      "${CMAKE_CURRENT_SOURCE_DIR}/.." "${CMAKE_SOURCE_DIR}/source/app")
   target_link_libraries(${input_target} PRIVATE acme apex aura PkgConfig::INPUT_XINPUT)
   if(NOT NO_PRECOMPILED_HEADER)
      target_precompile_headers(${input_target} PRIVATE platform.h)
   endif()
endforeach()
target_compile_definitions(static_input_xinput PRIVATE CUBE)
if(UNIX)
   target_link_options(input_xinput PRIVATE -Wl,-z,defs)
endif()
