cmake_minimum_required(VERSION 3.17)
project(audio_oss CXX)

set(oss_sources _.h platform.h _factory.cpp wave_out.h wave_out.cpp)
add_library(audio_oss SHARED ${oss_sources})
add_library(static_audio_oss STATIC ${oss_sources})
foreach(oss_target audio_oss static_audio_oss)
   target_include_directories(${oss_target} PRIVATE
      ${CMAKE_CURRENT_SOURCE_DIR} ${CMAKE_CURRENT_SOURCE_DIR}/..)
   target_compile_definitions(${oss_target} PRIVATE _audio_oss_project)
   if(NOT NO_PRECOMPILED_HEADER)
      target_precompile_headers(${oss_target} PRIVATE platform.h)
   endif()
endforeach()
target_compile_definitions(static_audio_oss PRIVATE CUBE)
target_link_libraries(audio_oss PRIVATE audio aqua apex acme)
target_link_libraries(static_audio_oss PRIVATE static_audio static_aqua static_apex static_acme)
if(__SUNOS__ OR __BSD__ OR LINUX)
   target_link_options(audio_oss PRIVATE -Wl,-z,defs)
endif()
